.github/workflows/pylint.yml
apps/xero/models.py

Added a traceback URL to the Fyle app to see the expense from the invoice.

Add Fyle expense redirection URL in Xero Bills

---

docker-compose.yml.template

Fixed the auto-restart problem after stopping the container and restarting the system again which blocked the port.

Docker-compose restart fix

---

apps/fyle/tasks.py
apps/workspaces/tasks.py
scripts/001-task-cleanup.sql

- Script for cleaning redundant entries in the tasks log.
- Methods update to have single fetching entry against a workspace.

Tasks Log Cleanup

---

.github/workflows/pytest.yml
apps/mappings/tasks.py
apps/xero/tasks.py
tests/test_mappings/test_tasks.py

[Sentry Platform error](https://fyle-technologies-private-limi.sentry.io/issues/4104196481/?environment=production&project=4505011377012736&query=is%3Aunresolved&referrer=issue-stream&stream_index=1)

Xero credential does not exist sentry error resolved

---

apps/xero/utils.py
requirements.txt
tests/test_xero/test_utils.py

This reverts commit bcaa7ef4ae17da38892d63ce754fac525759a658.

Revert "feat: Optimize Contacts Sync (#271)"

---

apps/xero/utils.py
tests/test_xero/test_utils.py

This reverts commit ef16cd26d2f211e1c7fd05927191e3d8203ce3e3.

`Revert "Revert "feat: Optimize Contacts Sync (#271)" (#272)"

---

apps/xero/utils.py

Added logging for the Payload of Exports

---

requirements.txt
tests/sql_fixtures/reset_db_fixtures/reset_db.sql

Fix activity mapping stats
[Handle Mappings for Activity Category](https://app.clickup.com/t/86cwkgp4t)

fix: activity mapping stats

---

fyle_xero_api/settings.py
requirements.txt

https://app.clickup.com/1864988/v/l/6-901603904304-1

feat: Added loggers in sdk and changed version

---

fyle_xero_api/sentry.py

https://app.clickup.com/t/86cx1jr57

fix: remove sentry transaction sampling

---

.gitmodules

fix: change the url of the submodule

---

.github/workflows/qa_deployment.yml

fix: update c1 deployment file

---

.github/workflows/qa_deployment.yml

fix: fix deployment workflow qa

---

requirements.txt

Bump accounting mapping version
https://app.clickup.com

chore: bump accounting mapping version

---

requirements.txt

fix: bump djangoq2
https://app.clickup.com/t/86cxq3fb5

fix: bump django q

---

apps/fyle/helpers.py

fix: Rounting Change

---

apps/fyle/helpers.py
apps/workspaces/tasks.py

fix: get access token

---

.github/workflows/qa_deployment.yml
.github/workflows/staging_deployment.yml

chore: deploy to all staging envs

---

tests/test_exceptions.py
tests/test_xero/test_exceptions.py

https://app.clickup.com/t/86cxhfm6w

test: unit test updates for comment fixes

---

apps/exceptions.py
apps/mappings/actions.py
apps/mappings/exceptions.py
apps/workspaces/actions.py
apps/workspaces/helpers.py
apps/xero/exceptions.py
apps/xero/queue.py
apps/xero/tasks.py
tests/test_exceptions.py
tests/test_xero/test_exceptions.py

https://app.clickup.com/t/86cxhfuuh

fix: token expiry logic

---

apps/exceptions.py
apps/mappings/actions.py
apps/mappings/exceptions.py
apps/workspaces/actions.py
apps/workspaces/helpers.py
apps/workspaces/tasks.py
apps/xero/exceptions.py
apps/xero/queue.py
apps/xero/tasks.py
tests/test_exceptions.py
tests/test_workspaces/test_actions.py
tests/test_workspaces/test_views.py
tests/test_xero/test_exceptions.py

https://app.clickup.com/t/86cxhfuuh

feat: patch `/integrations` on token expiry

---

apps/exceptions.py
apps/fyle/helpers.py
apps/mappings/actions.py
apps/mappings/exceptions.py
apps/workspaces/actions.py
apps/workspaces/helpers.py
apps/workspaces/tasks.py
apps/xero/exceptions.py
apps/xero/queue.py
apps/xero/tasks.py
tests/test_exceptions.py
tests/test_workspaces/test_actions.py
tests/test_workspaces/test_views.py
tests/test_xero/test_exceptions.py

https://app.clickup.com/t/86cxhftnk

feat: PATCH `/integrations` on export errors

---

apps/workspaces/views.py

https://app.clickup.com/t/86cxhftnk

fix: POST to `/integrations` on disconnect and reconnect

---

fyle_xero_api/sentry.py

fix: pii
https://app.clickup.com/t/86cxygv7h

fix: sentry pii

---

apps/fyle/tasks.py
apps/fyle/views.py
apps/workspaces/tasks.py
tests/test_fyle/test_task.py

fix: Rename func

---

health_check.sh

fix: health check

---

.flake8
requirements.txt
workers/export/worker.py

fix: bump version and add few more loggers

---

fyle_xero_api/settings.py
workers/export/worker.py

fix: logging format to be same as other modules

---

apps/fyle/queue.py
apps/fyle/tasks.py
apps/xero/exceptions.py
tests/test_xero/test_exceptions.py

fix: filter expenses based on state only for webhook calls | few more bug fixes as part of realtime imports

---

apps/internal/tasks.py
requirements.txt

fix: Retry stuck tasks export

---

apps/xero/queue.py

fix: trigger_by in task_logs

---

.flake8
Dockerfile
docker-compose-pipeline.yml
init.sql
tests/conftest.py
tests/sql_fixtures/reset_db_fixtures/reset_db.sh

fix: TLS vulnerability

---

apps/xero/exceptions.py

fix: Add 1 general post accounting call after last export

fix: Add 1 general post accounting call after last export

---

apps/internal/tasks.py

fix: Retry Stuck Tasks bug

---

apps/workspaces/apis/import_settings/serializers.py
apps/workspaces/apis/import_settings/triggers.py

feat: mapping settings change

---

apps/fyle/actions.py
apps/fyle/models.py
apps/internal/tasks.py
apps/mappings/tasks.py
apps/workspaces/apis/import_settings/triggers.py
apps/xero/tasks.py

Feat: Add updated_at to update and bulk_update

---

apps/fyle/tasks.py

fix: exception handling in import of expenses

---

apps/internal/migrations/0001_auto_generated_sql.py

https://app.clickup.com/1864988/v/l/li/901605343641

Feat: Added replication queries

---

requirements.txt
tests/sql_fixtures/reset_db_fixtures/reset_db.sql
tests/test_workspaces/test_email.py

fix: new migration changes tests

---

tests/test_users/test_models.py

https://app.clickup.com/1864988/v/l/li/901605343641

Feat: Dummy Commit

---

Dockerfile

fix: update setuptools, wheel

---

apps/fyle/actions.py
apps/fyle/tasks.py
apps/workspaces/actions.py
apps/xero/exceptions.py
apps/xero/tasks.py
scripts/python/post-accounting-export-summary.py
tests/test_fyle/test_task.py

feat: Invalid token fix direct export

feat: Invalid token fix direct export

---

apps/xero/tasks.py
requirements.txt
scripts/python/001_fill_xero_and_fyle_currency.py
tests/conftest.py
tests/test_fyle/test_actions.py
tests/test_fyle/test_task.py
tests/test_fyle/test_views.py
tests/test_fyle_integrations_imports/test_modules/test_base.py
tests/test_mappings/test_signals.py
tests/test_mappings/test_tasks.py
tests/test_users/test_helpers.py
tests/test_workspaces/test_apis/test_import_settings/test_views.py
tests/test_workspaces/test_tasks.py
tests/test_xero/test_tasks.py

feat: move to v1

---

apps/xero/tasks.py

chore: Handle Process Reimbursement

chore: Handle Process Reimbursement

---

requirements.txt
tests/sql_fixtures/reset_db_fixtures/reset_db.sql

chore: bump libraries

---

apps/fyle/models.py
apps/xero/models.py

fix: last spent at configuration
https://app.clickup.com/t/86cypg5dj

fix: last spent at configuration

---

apps/internal/tasks.py

fix: Expense group get for internal fun
https://app.clickup.com/t/86cyq6u62

fix: Expense group get for internal fun

---

apps/internal/tasks.py

fix: add expense group condition
https://app.clickup.com/t/86cyq6u62

fix: add expense group condition

---

apps/fyle/actions.py
apps/internal/tasks.py

fix: Reduce paginator size for accounting export summary post
https://app.clickup.com/t/86cytytzb

fix: Reduce paginator size for accounting export summary post

---

apps/fyle/actions.py
apps/xero/queue.py

fix: skip direct export call

---

requirements.txt

https://app.clickup.com/1864988/v/l/li/901605343641

Feat: Bump up integration platform conector version

---

apps/workspaces/queue.py

fix: schedule and email creation/deletion case

---

apps/workspaces/queue.py

fix: schedule deletion while switching to real-time

---

apps/fyle/tasks.py

fix: direct export token bug

---

apps/fyle/actions.py
apps/xero/tasks.py
fyle_xero_api/logging_middleware.py

chore: Add direct export loggers

chore: Add direct export loggers

---

fyle_xero_api/settings.py

feat: Remove Timeout from qcluster settings
Please add link here

feat: Remove Timeout from qcluster settings

---

apps/xero/queue.py
tests/test_xero/conftest.py
tests/test_xero/test_tasks.py

- Added functionality to update last export details when skipping the last expense group during bill, cheque, journal entry, credit card purchase, and Xero expense creation.
- Improved handling of last export condition to ensure accurate tracking of export status.

fix: Enhance export scheduling by updating last export details

---

health_check.sh

feat: update health_check to check for consumer liveness

---

apps/workspaces/actions.py

fix: update failed param

---

fyle_xero_api/settings.py

fix: Timeout Warning

---

.pre-commit-config.yaml

fix: pre commit

---

fyle_xero_api/settings.py

Feat: Fix throttling vulnerability

---

apps/internal/tasks.py

fix: internal function

---

requirements.txt

fix: tax amount none
https://app.clickup.com/t/86cztddtb

chore: Update fyle-integrations-platform-connector to 2.3.5

---

apps/workspaces/templates/mail_template.html

feat: rebrand mail template
